description = "Once-prosperous Coriolis was broken by war between Utopia, Myrmidon, and Coriolis itself. Stripped nobles and survivors trade in caravans, melt relics into guns, herd engineered Ceph for wealth, and cling to governance from the ruins while the old dynasty’s corpse is slowly built over.\n"

[[cards]]
image = "01.jpg"
name = "Bull Ceph"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 4

[[cards]]
image = "02.jpg"
name = "Caravan Guards"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 4

[[cards]]
image = "03.jpg"
name = "Duchess Of Ash"
type = "unit"
type_secondary = [
    "human",
]
cost = 4

[[cards]]
image = "04.jpg"
name = "Duelist"
type = "augment"
type_secondary = [
    "unit",
]
cost = 2

[[cards]]
image = "05.jpg"
name = "Field Medics"
type = "unit"
type_secondary = [
    "human",
]
cost = 2

[[cards]]
image = "06.jpg"
name = "Flagbearers"
type = "unit"
type_secondary = [
    "human",
]
cost = 3

[[cards]]
image = "07.jpg"
name = "Frontier Despot"
type = "unit"
type_secondary = [
    "human",
]
cost = 2

[[cards]]
image = "08.jpg"
name = "Gardens Of Kadesh"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "09.jpg"
name = "Glacial Melt"
type = "reflex"
cost = 0

[[cards]]
image = "10.jpg"
name = "Graftguard"
type = "unit"
type_secondary = [
    "human",
]
cost = 4

[[cards]]
image = "11.jpg"
name = "High Caste"
type = "augment"
type_secondary = [
    "unit",
]
cost = 2

[[cards]]
image = "12.jpg"
name = "Highborn Academy"
type = "colony"
type_secondary = [
    "facility",
]
cost = 3

[[cards]]
image = "13.jpg"
name = "Highborn Nursery"
type = "colony"
type_secondary = [
    "facility",
]
cost = 3

[[cards]]
image = "14.jpg"
name = "Ice Hauler"
type = "unit"
type_secondary = [
    "mech",
]
cost = 3

[[cards]]
image = "15.jpg"
name = "Merchant Caravan"
type = "unit"
type_secondary = [
    "human",
    "xeno",
]
cost = 3

[[cards]]
image = "16.jpg"
name = "Migrant Labor"
type = "reflex"
cost = 0

[[cards]]
image = "17.jpg"
name = "Mule"
type = "augment"
type_secondary = [
    "unit",
]
cost = 3

[[cards]]
image = "18.jpg"
name = "Musk Ceph"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 3

[[cards]]
image = "19.jpg"
name = "Noble Profession"
type = "augment"
type_secondary = [
    "facility",
]
cost = 3

[[cards]]
image = "20.jpg"
name = "Open Market"
type = "colony"
type_secondary = [
    "facility",
]
cost = 3

[[cards]]
image = "21.jpg"
name = "Plutocracy"
type = "reflex"
cost = 1

[[cards]]
image = "22.jpg"
name = "Prodigal Sons"
type = "reflex"
cost = 4

[[cards]]
image = "23.jpg"
name = "Rail Cavalry"
type = "unit"
type_secondary = [
    "antigrav",
]
cost = 5

[[cards]]
image = "24.jpg"
name = "Relocation"
type = "reflex"
cost = 2

[[cards]]
image = "25.jpg"
name = "Ruined Arcology"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "26.jpg"
name = "Scrap Hunt"
type = "reflex"
cost = 1

[[cards]]
image = "27.jpg"
name = "Scrap Scavengers"
type = "unit"
type_secondary = [
    "human",
]
cost = 3

[[cards]]
image = "28.jpg"
name = "Stun Whip"
type = "augment"
type_secondary = [
    "unit",
]
cost = 2

[[cards]]
image = "29.jpg"
name = "Synthsilk Hatchery"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "30.jpg"
name = "Technocrats"
type = "unit"
type_secondary = [
    "human",
]
cost = 0
