description = "First people out of the wrecked ark; they claim Apsyntion, not Earth, as home. Semi-nomadic clans live beside Lilin hives, coaxing food and oxygen from the fungal mat while oral tradition hides Wormwood’s grave—Wind Cathedrals on the cliffs echo hive-song at dawn and dusk.\n"

[[cards]]
image = "01.jpg"
name = "Anemoi"
type = "unit"
type_secondary = [
    "human",
]
cost = 3

[[cards]]
image = "02.jpg"
name = "Apsyntion Communication"
type = "reflex"
cost = 0

[[cards]]
image = "03.jpg"
name = "Apsyntion Symbiosis"
type = "reflex"
cost = 1

[[cards]]
image = "04.jpg"
name = "Behemoth"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 8

[[cards]]
image = "05.jpg"
name = "Borespikes"
type = "augment"
type_secondary = [
    "unit",
]
cost = 5

[[cards]]
image = "06.jpg"
name = "Boreworm"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 5

[[cards]]
image = "07.jpg"
name = "Brood Den"
type = "colony"
type_secondary = [
    "facility",
]
cost = 3

[[cards]]
image = "08.jpg"
name = "Brood Handlers"
type = "unit"
type_secondary = [
    "chimera",
]
cost = 3

[[cards]]
image = "09.jpg"
name = "Bury"
type = "reflex"
cost = 1

[[cards]]
image = "10.jpg"
name = "Chrysalis"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 2

[[cards]]
image = "11.jpg"
name = "Contact"
type = "reflex"
cost = 1

[[cards]]
image = "12.jpg"
name = "Flock Webs"
type = "augment"
type_secondary = [
    "unit",
]
cost = 2

[[cards]]
image = "13.jpg"
name = "Fungus Farm"
type = "colony"
type_secondary = [
    "facility",
]
cost = 2

[[cards]]
image = "14.jpg"
name = "Harlequin"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 4

[[cards]]
image = "15.jpg"
name = "Incursion"
type = "reflex"
cost = 2

[[cards]]
image = "16.jpg"
name = "Lilin Hive"
type = "colony"
type_secondary = [
    "facility",
]
cost = 2

[[cards]]
image = "17.jpg"
name = "Lilin Matron"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 4

[[cards]]
image = "18.jpg"
name = "Lilin Vultures"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 2

[[cards]]
image = "19.jpg"
name = "Mark Of The Hive"
type = "augment"
type_secondary = [
    "facility",
]
cost = 2

[[cards]]
image = "20.jpg"
name = "Mimetic Scales"
type = "augment"
type_secondary = [
    "unit",
]
cost = 2

[[cards]]
image = "21.jpg"
name = "Musk Herders"
type = "unit"
type_secondary = [
    "human",
]
cost = 2

[[cards]]
image = "22.jpg"
name = "Shroud"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 3

[[cards]]
image = "23.jpg"
name = "Spawning Pits"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "24.jpg"
name = "Spore Weevils"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 5

[[cards]]
image = "25.jpg"
name = "Sporemask Poachers"
type = "unit"
type_secondary = [
    "human",
]
cost = 4

[[cards]]
image = "26.jpg"
name = "Wind Cathedral"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "27.jpg"
name = "Windlion"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 4

[[cards]]
image = "28.jpg"
name = "Windwalker Camp"
type = "colony"
type_secondary = [
    "facility",
]
cost = 3

[[cards]]
image = "29.jpg"
name = "Xeno Psychology"
type = "reflex"
cost = 1

[[cards]]
image = "30.jpg"
name = "Xenophagy"
type = "augment"
type_secondary = [
    "unit",
]
cost = 2
