description = "Apsyntion’s oldest human-native faith, fanatically xenophobic toward alien and machine alike. The Maestra leads religion and war; the Choir and Inquisitors enforce doctrine in scattered chapels, preaching that Wormwood is the key to humanity’s return to Old Terra’s garden.\n"

[[cards]]
image = "01.jpg"
name = "Absolution Sphere"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "02.jpg"
name = "Acid Baptists"
type = "unit"
type_secondary = [
    "human",
]
cost = 3

[[cards]]
image = "03.jpg"
name = "Ascetic Virtues"
type = "reflex"
cost = 1

[[cards]]
image = "04.jpg"
name = "Clinical Immortality"
type = "augment"
type_secondary = [
    "unit",
]
cost = 4

[[cards]]
image = "05.jpg"
name = "Crecheling Prophet"
type = "unit"
type_secondary = [
    "human",
]
cost = 3

[[cards]]
image = "06.jpg"
name = "Desertion"
type = "reflex"
cost = 2

[[cards]]
image = "07.jpg"
name = "Deva Monks"
type = "unit"
type_secondary = [
    "human",
]
cost = 4

[[cards]]
image = "08.jpg"
name = "Gravelinks"
type = "augment"
type_secondary = [
    "unit",
]
cost = 2

[[cards]]
image = "09.jpg"
name = "Halo Lift"
type = "colony"
type_secondary = [
    "facility",
]
cost = 3

[[cards]]
image = "10.jpg"
name = "Holy Day"
type = "reflex"
cost = 3

[[cards]]
image = "11.jpg"
name = "House Of Meditation"
type = "colony"
type_secondary = [
    "facility",
]
cost = 3

[[cards]]
image = "12.jpg"
name = "Hymn Of Knitting"
type = "augment"
type_secondary = [
    "unit",
]
cost = 2

[[cards]]
image = "13.jpg"
name = "Inquisitors"
type = "unit"
type_secondary = [
    "human",
]
cost = 3

[[cards]]
image = "14.jpg"
name = "Jetleap Seraphim"
type = "unit"
type_secondary = [
    "human",
]
cost = 3

[[cards]]
image = "15.jpg"
name = "Library Of The Ark"
type = "colony"
type_secondary = [
    "facility",
]
cost = 3

[[cards]]
image = "16.jpg"
name = "Maestra Sangha"
type = "unit"
type_secondary = [
    "human",
]
cost = 4

[[cards]]
image = "17.jpg"
name = "Messenger Ferry"
type = "unit"
type_secondary = [
    "antigrav",
]
cost = 0

[[cards]]
image = "18.jpg"
name = "Miraculous Escape"
type = "reflex"
cost = 1

[[cards]]
image = "19.jpg"
name = "Neogenesis Chapel"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "20.jpg"
name = "Pious Devotion"
type = "augment"
type_secondary = [
    "unit",
]
cost = 3

[[cards]]
image = "21.jpg"
name = "Relic Seekers"
type = "unit"
type_secondary = [
    "human",
]
cost = 2

[[cards]]
image = "22.jpg"
name = "Seraphim Choir"
type = "unit"
type_secondary = [
    "human",
]
cost = 6

[[cards]]
image = "23.jpg"
name = "Symmetric Supplication"
type = "reflex"
cost = 2

[[cards]]
image = "24.jpg"
name = "Terra Ascetics"
type = "unit"
type_secondary = [
    "human",
]
cost = 2

[[cards]]
image = "25.jpg"
name = "Terra Colossus"
type = "colony"
type_secondary = [
    "facility",
]
cost = 3

[[cards]]
image = "26.jpg"
name = "Theocracy"
type = "augment"
type_secondary = [
    "facility",
]
cost = 6

[[cards]]
image = "27.jpg"
name = "Trench Judges"
type = "unit"
type_secondary = [
    "human",
]
cost = 3

[[cards]]
image = "28.jpg"
name = "Webweave Cherubs"
type = "unit"
type_secondary = [
    "human",
]
cost = 3

[[cards]]
image = "29.jpg"
name = "White Bishops"
type = "unit"
type_secondary = [
    "human",
]
cost = 3

[[cards]]
image = "30.jpg"
name = "Zealotry"
type = "reflex"
cost = 2
