description = "They settle the fungal wastes’ most toxic psychoactive zones and Lilin husks, obeying laws shaped by semi-aware xenofungus. Initiates splice mycelium into flesh until the network owns their nerves—gaining strength and spore-born “telepathy” while spreading infection toward a holy end to mankind.\n"

[[cards]]
image = "01.jpg"
name = "Acid Husks"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 4

[[cards]]
image = "02.jpg"
name = "Apsyntion Preserve"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "03.jpg"
name = "Blister Plates"
type = "augment"
type_secondary = [
    "unit",
]
cost = 2

[[cards]]
image = "04.jpg"
name = "Boreworm Larvae"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 4

[[cards]]
image = "05.jpg"
name = "Carrier"
type = "augment"
type_secondary = [
    "unit",
]
cost = 4

[[cards]]
image = "06.jpg"
name = "Chimera Guild"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "07.jpg"
name = "Elder Hybrids"
type = "unit"
type_secondary = [
    "chimera",
]
cost = 3

[[cards]]
image = "08.jpg"
name = "Endospexi"
type = "unit"
type_secondary = [
    "chimera",
]
cost = 2

[[cards]]
image = "09.jpg"
name = "Fungal Bloom"
type = "reflex"
cost = 3

[[cards]]
image = "10.jpg"
name = "Gene Speakers"
type = "unit"
type_secondary = [
    "chimera",
]
cost = 3

[[cards]]
image = "11.jpg"
name = "Hyphal Warning"
type = "augment"
type_secondary = [
    "unit",
]
cost = 3

[[cards]]
image = "12.jpg"
name = "Grendels"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 5

[[cards]]
image = "13.jpg"
name = "Haruspexi"
type = "unit"
type_secondary = [
    "chimera",
]
cost = 3

[[cards]]
image = "14.jpg"
name = "Herdmasters"
type = "unit"
type_secondary = [
    "chimera",
]
cost = 3

[[cards]]
image = "15.jpg"
name = "Mosaic Mutation"
type = "reflex"
cost = 2

[[cards]]
image = "16.jpg"
name = "Mycandrium"
type = "colony"
type_secondary = [
    "facility",
]
cost = 3

[[cards]]
image = "17.jpg"
name = "Mygologists"
type = "unit"
type_secondary = [
    "human",
]
cost = 2

[[cards]]
image = "18.jpg"
name = "Orthogenesis"
type = "reflex"
cost = 2

[[cards]]
image = "19.jpg"
name = "Plague Spores"
type = "reflex"
cost = 2

[[cards]]
image = "20.jpg"
name = "Planet Plague"
type = "augment"
type_secondary = [
    "unit",
]
cost = 2

[[cards]]
image = "21.jpg"
name = "Rot Midden"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "22.jpg"
name = "Silkspitters"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 4

[[cards]]
image = "23.jpg"
name = "Spore Blossoms"
type = "augment"
type_secondary = [
    "unit",
]
cost = 2

[[cards]]
image = "24.jpg"
name = "Spore Mats"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "25.jpg"
name = "Spore Slaves"
type = "unit"
type_secondary = [
    "human",
]
cost = 2

[[cards]]
image = "26.jpg"
name = "Spore Storm"
type = "reflex"
cost = 2

[[cards]]
image = "27.jpg"
name = "Stalk Tenders"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 2

[[cards]]
image = "28.jpg"
name = "Unruly Husks"
type = "unit"
type_secondary = [
    "xeno",
]
cost = 3

[[cards]]
image = "29.jpg"
name = "Xeno Regeneration"
type = "reflex"
cost = 1

[[cards]]
image = "30.jpg"
name = "Kenoneural Arcology"
type = "colony"
type_secondary = [
    "facility",
]
cost = 5
