description = "Nomadic marauders from the fungal wastes to the southern ice line, infamous for past wars yet surprisingly meritocratic among soldiers. They field mechs and exosuits, despise synths, and drive legions into frenzy with “battle hymns” from battlefield minarets.\n"

[[cards]]
image = "01.jpg"
name = "Battle Stims"
type = "augment"
type_secondary = [
    "unit",
]
cost = 2

[[cards]]
image = "02.jpg"
name = "Burnout"
type = "reflex"
cost = 1

[[cards]]
image = "03.jpg"
name = "Conscription"
type = "reflex"
cost = 1

[[cards]]
image = "04.jpg"
name = "Defensive Position"
type = "reflex"
cost = 2

[[cards]]
image = "05.jpg"
name = "Drillyard"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "06.jpg"
name = "Firehawk Bomber"
type = "unit"
type_secondary = [
    "antigrav",
]
cost = 5

[[cards]]
image = "07.jpg"
name = "Flesh Spare"
type = "augment"
type_secondary = [
    "unit",
]
cost = 3

[[cards]]
image = "08.jpg"
name = "Flux Ammo"
type = "reflex"
cost = 4

[[cards]]
image = "09.jpg"
name = "Geneforge"
type = "colony"
type_secondary = [
    "facility",
]
cost = 3

[[cards]]
image = "10.jpg"
name = "Goliath Cannon"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "11.jpg"
name = "Iron Oni"
type = "unit"
type_secondary = [
    "human",
]
cost = 4

[[cards]]
image = "12.jpg"
name = "Lascannon Heavies"
type = "unit"
type_secondary = [
    "mech",
]
cost = 4

[[cards]]
image = "13.jpg"
name = "Link Crown"
type = "augment"
type_secondary = [
    "unit",
]
cost = 2

[[cards]]
image = "14.jpg"
name = "Lotus Eaters"
type = "unit"
type_secondary = [
    "human",
]
cost = 3

[[cards]]
image = "15.jpg"
name = "Martial Law"
type = "reflex"
cost = 0

[[cards]]
image = "16.jpg"
name = "Mech Foundry"
type = "colony"
type_secondary = [
    "facility",
]
cost = 3

[[cards]]
image = "17.jpg"
name = "Mech Junkies"
type = "unit"
type_secondary = [
    "human",
]
cost = 0

[[cards]]
image = "18.jpg"
name = "Military Academy"
type = "colony"
type_secondary = [
    "facility",
]
cost = 3

[[cards]]
image = "19.jpg"
name = "Newbloods"
type = "unit"
type_secondary = [
    "human",
]
cost = 3

[[cards]]
image = "20.jpg"
name = "Powered Exoskeleton"
type = "augment"
type_secondary = [
    "unit",
]
cost = 3

[[cards]]
image = "21.jpg"
name = "Salamander Armor"
type = "unit"
type_secondary = [
    "mech",
]
cost = 4

[[cards]]
image = "22.jpg"
name = "Shock Troops"
type = "unit"
type_secondary = [
    "human",
]
cost = 5

[[cards]]
image = "23.jpg"
name = "Slave Battalion"
type = "unit"
type_secondary = [
    "human",
]
cost = 2

[[cards]]
image = "24.jpg"
name = "Stiltstrider"
type = "unit"
type_secondary = [
    "mech",
]
cost = 7

[[cards]]
image = "25.jpg"
name = "Striker Mech"
type = "unit"
type_secondary = [
    "mech",
]
cost = 5

[[cards]]
image = "26.jpg"
name = "Synthsilk Platoon"
type = "unit"
type_secondary = [
    "human",
]
cost = 7

[[cards]]
image = "27.jpg"
name = "Tundra Palace"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "28.jpg"
name = "Veteran Plate"
type = "augment"
type_secondary = [
    "unit",
]
cost = 5

[[cards]]
image = "29.jpg"
name = "War Chiefs"
type = "unit"
type_secondary = [
    "human",
]
cost = 4

[[cards]]
image = "30.jpg"
name = "Warthirst"
type = "reflex"
cost = 0
