description = "Escaped drones—often from the Undercity—built a militant, trade-hungry enclave of equals. They copy and field scavenged war tech, wage a hidden war of hacks and knives to free their kind, and would turn Wormwood’s power against every chain.\n"

[[cards]]
image = "01.jpg"
name = "Apsynthos Cryopod"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "02.jpg"
name = "Apsynthos Memorial"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "03.jpg"
name = "Calliope"
type = "unit"
type_secondary = [
    "antigrav",
]
cost = 4

[[cards]]
image = "04.jpg"
name = "Cantina"
type = "colony"
type_secondary = [
    "facility",
]
cost = 3

[[cards]]
image = "05.jpg"
name = "Defection"
type = "reflex"
cost = 3

[[cards]]
image = "06.jpg"
name = "Desperate Sacrifice"
type = "reflex"
cost = 1

[[cards]]
image = "07.jpg"
name = "Detonation Packs"
type = "augment"
type_secondary = [
    "unit",
]
cost = 2

[[cards]]
image = "08.jpg"
name = "Double Agent"
type = "augment"
type_secondary = [
    "unit",
]
cost = 2

[[cards]]
image = "09.jpg"
name = "Drone Insurgents"
type = "unit"
type_secondary = [
    "human",
]
cost = 3

[[cards]]
image = "10.jpg"
name = "Drone Riots"
type = "reflex"
cost = 2

[[cards]]
image = "11.jpg"
name = "Dustmen"
type = "unit"
type_secondary = [
    "human",
]
cost = 3

[[cards]]
image = "12.jpg"
name = "Hive Radicals"
type = "unit"
type_secondary = [
    "human",
]
cost = 3

[[cards]]
image = "13.jpg"
name = "Holonet Scribes"
type = "unit"
type_secondary = [
    "human",
]
cost = 2

[[cards]]
image = "14.jpg"
name = "Infoleak"
type = "reflex"
cost = 2

[[cards]]
image = "15.jpg"
name = "Nano Plantation"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "16.jpg"
name = "Nerve Plates"
type = "augment"
type_secondary = [
    "unit",
]
cost = 2

[[cards]]
image = "17.jpg"
name = "Plasma Torch"
type = "augment"
type_secondary = [
    "unit",
]
cost = 3

[[cards]]
image = "18.jpg"
name = "Rail Sniper"
type = "unit"
type_secondary = [
    "human",
]
cost = 4

[[cards]]
image = "19.jpg"
name = "Recon Guerillas"
type = "unit"
type_secondary = [
    "human",
]
cost = 4

[[cards]]
image = "20.jpg"
name = "Refugee Ethics"
type = "reflex"
cost = 3

[[cards]]
image = "21.jpg"
name = "Sabotage"
type = "reflex"
cost = 3

[[cards]]
image = "22.jpg"
name = "Scrap Depot"
type = "colony"
type_secondary = [
    "facility",
]
cost = 3

[[cards]]
image = "23.jpg"
name = "Sentinels"
type = "unit"
type_secondary = [
    "mech",
]
cost = 6

[[cards]]
image = "24.jpg"
name = "Skimsquad"
type = "unit"
type_secondary = [
    "antigrav",
]
cost = 6

[[cards]]
image = "25.jpg"
name = "Splicing Medics"
type = "unit"
type_secondary = [
    "human",
]
cost = 2

[[cards]]
image = "26.jpg"
name = "Stitch Tanks"
type = "colony"
type_secondary = [
    "facility",
]
cost = 4

[[cards]]
image = "27.jpg"
name = "Undercity Anarchs"
type = "unit"
type_secondary = [
    "human",
]
cost = 2

[[cards]]
image = "28.jpg"
name = "Watchdogs"
type = "unit"
type_secondary = [
    "mech",
]
cost = 5

[[cards]]
image = "29.jpg"
name = "Webweave Spies"
type = "unit"
type_secondary = [
    "human",
]
cost = 3

[[cards]]
image = "30.jpg"
name = "Worker Strike"
type = "augment"
type_secondary = [
    "facility",
]
cost = 2
